name: mgba
base: core18
license: MPL-2.0
adopt-info: mgba
summary: mGBA Game Boy Advance Emulator https://mgba.io/
description: |
  mGBA is an emulator for running Game Boy Advance games. It aims to be faster
  and more accurate than many existing Game Boy Advance emulators, as well as
  adding features that other emulators lack. It also supports Game Boy and
  Game Boy Color games.

architectures:
  - build-on: i386
  - build-on: amd64

confinement: strict
grade: stable

plugs: # additional plugs to pick up the GTK theme and icons from the system
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  gtk-2-engines:
    interface: content
    target: $SNAP/lib/gtk-2.0
    default-provider: gtk2-common-themes:gtk-2-engines
  gtk-2-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk2-common-themes:gtk-2-themes

apps:
  mgba-qt:
    environment:
      XLOCALEDIR: '$SNAP/usr/share/X11/locale'
      LOCPATH: '$SNAP/usr/lib/locale'
      GTK_PATH: $SNAP/lib/gtk-2.0
      GTK_DATA_PREFIX: $SNAP
      XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS
      XDG_CONFIG_HOME: '$HOME/.config'
      XKB_CONFIG_ROOT: '$SNAP/usr/share/X11/xkb'
      XDG_CONFIG_DIRS: '$SNAP/etc/xdg:$XDG_CONFIG_DIRS'
      XDG_DATA_HOME: '$SNAP/usr/share'
      DISABLE_WAYLAND: '1'
      LD_LIBRARY_PATH: '$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$LD_LIBRARY_PATH'
      QT_QPA_PLATFORMTHEME: gtk2 # set default theme to gtk to integrate with system theme (GTK2)
    command: desktop-launch mgba-qt
    plugs:
      - x11
      - home
      - audio-playback
      - opengl
      - joystick
      - network
  mgba:
    environment:
      XLOCALEDIR: '$SNAP/usr/share/X11/locale'
      LOCPATH: '$SNAP/usr/lib/locale'
      XDG_CONFIG_HOME: '$HOME/.config'
      XKB_CONFIG_ROOT: '$SNAP/usr/share/X11/xkb'
      XDG_CONFIG_DIRS: '$SNAP/etc/xdg:$XDG_CONFIG_DIRS'
      XDG_DATA_HOME: '$SNAP/usr/share'
      LD_LIBRARY_PATH: '$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$LD_LIBRARY_PATH'
    command: mgba
    plugs:
      - x11
      - home
      - audio-playback
      - opengl
      - joystick
      - network

parts:
  mgba:
    after: [desktop-qt5]
    plugin: cmake
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git tag | grep ^0 | sort -V | tail -n 1)"
      last_released_tag="$(snap info mgba | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
        cd ../src
        snapcraftctl set-version "${last_committed_tag}"
      else
        git checkout master
        snapcraftctl set-version "git"
      fi
      snapcraftctl build
      
    configflags:
      - -DCMAKE_INSTALL_PREFIX:PATH=/usr
      - -DUPDATE_TRANSLATIONS=ON
      - -DUSE_DISCORD_RPC=OFF
    source: https://github.com/mgba-emu/mgba.git
    build-packages:
      - libavcodec-dev
      - libavfilter-dev
      - libavformat-dev
      - libavresample-dev
      - libavutil-dev
      - libedit-dev
      - libelf-dev
      - libepoxy-dev
      - libgail-dev
      - libmagickwand-dev
      - libminizip-dev
      - libpixman-1-dev
      - libpng-dev
      - libqt5opengl5-dev
      - libsdl2-dev
      - libsqlite3-dev
      - libswscale-dev
      - libzip-dev
      - qtbase5-dev
      - qtdeclarative5-dev
      - qtmultimedia5-dev
      - qttools5-dev
      - qttools5-dev-tools
      - qttranslations5-l10n
      - zlib1g-dev
    stage-packages:
      - libatk-adaptor
      - libavfilter6
      - libavformat57
      - libavresample3
      - libavutil55
      - libbluray2
      - libcrystalhd3
      - libelf1
      - libepoxy0
      - libfftw3-double3
      - libgail-common
      - libgme0
      - libgomp1
      - libgsm1
      - liblqr-1-0
      - libltdl7
      - libmagickcore-6.q16-3
      - libmagickwand-6.q16-3
      - libmodplug1
      - libmp3lame0
      - libnuma1
      - libopenjp2-7
      - libopus0
      - libqt5multimedia5
      - libqt5multimedia5-plugins
      - libqt5qml5
      - librtmp1
      - libsdl2-2.0-0
      - libshine3
      - libsnappy1v5
      - libsndio6.1
      - libsoxr0
      - libspeex1
      - libssh-gcrypt-4
      - libswresample2
      - libswscale4
      - libtheora0
      - libtwolame0
      - libva2
      - libvpx5
      - libwavpack1
      - libwebp6
      - libx264-152
      - libx265-146
      - libxss1
      - libxvidcore4
      - libzip4
      - libzvbi0
      - qt5-style-plugins
      - qttranslations5-l10n

  desktop-qt5:
    build-packages:
    - build-essential
    - qtbase5-dev
    - dpkg-dev
    make-parameters:
    - FLAVOR=qt5
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    stage-packages:
    - libxkbcommon0
    - ttf-ubuntu-font-family
    - dmz-cursor-theme
    - light-themes
    - adwaita-icon-theme
    - gnome-themes-standard
    - shared-mime-info
    - libqt5gui5
    - libgdk-pixbuf2.0-0
    - libqt5svg5
    - try:
      - appmenu-qt5
    - locales-all
    - xdg-user-dirs
    - fcitx-frontend-qt5
